Test Debian 8 and 9 packages.

diff --git a/tests/package/Makefile b/tests/package/Makefile
--- a/tests/package/Makefile
+++ b/tests/package/Makefile
@@ -5,8 +5,8 @@ default: all
 
 clean:
 	rm -rf target/*
-	docker rmi -f marathon-package-test:debian-systemd || echo "Couldn't remove debian-systemd"
-	docker rmi -f marathon-package-test:debian-systemv || echo "Couldn't remove debian-systemv"
+	docker rmi -f marathon-package-test:debian8 || echo "Couldn't remove debian-systemd"
+	docker rmi -f marathon-package-test:debian9 || echo "Couldn't remove debian-systemv"
 	docker rmi -f marathon-package-test:mesos || echo "Couldn't remove mesos"
 
 %/mesos-version: target/mesos-version
@@ -14,10 +14,10 @@ clean:
 
 # 1.5.0-2.0.1 package has issues for Debian, and 1.5.0-2.0.2 isn't released for all distros. When we move past this,
 # remove these build steps
-debian-systemv/mesos-version: target/mesos-version
+debian8/mesos-version: target/mesos-version
 	if [ $$(cat target/mesos-version) = "1.5.0-2.0.1" ]; then echo "1.5.0-2.0.2" > $@; else echo "Package version patch should not be needed; remove this step from the Makefile"; exit 1; fi
 
-debian-systemd/mesos-version: target/mesos-version
+debian9/mesos-version: target/mesos-version
 	if [ $$(cat target/mesos-version) = "1.5.0-2.0.1" ]; then echo "1.5.0-2.0.2" > $@; else echo "Package version patch should not be needed; remove this step from the Makefile"; exit 1; fi
 
 ubuntu-upstart/mesos-version: target/mesos-version
@@ -29,16 +29,12 @@ target/mesos-version: ../../project/Dependencies.scala
 	[ "$$(wc -l $@.tmp | awk '{print $$1}')" = 1 ]
 	mv $@.tmp $@
 
-target/debian-systemd.built: debian-systemd/Dockerfile debian-systemd/mesos-version
-	cd debian-systemd && docker build . -t marathon-package-test:debian-systemd
+target/debian8.built: debian8/Dockerfile debian8/mesos-version
+	cd debian8 && docker build . -t marathon-package-test:debian8
 	mkdir -p target
 	touch $@
 
-target/debian-systemv.built: target/debian-systemd.built debian-systemv/Dockerfile
-	cd debian-systemv && docker build . -t marathon-package-test:debian-systemv
-	touch $@
-
-target/mesos.built: target/debian-systemd.built mesos/Dockerfile
+target/mesos.built: target/debian8.built mesos/Dockerfile
 	cd mesos && docker build . -t marathon-package-test:mesos
 	touch $@
 
@@ -57,4 +53,4 @@ target/ubuntu-upstart.built: ubuntu-upstart/Dockerfile ubuntu-upstart/mesos-vers
 test: | all
 	amm test.sc all
 
-all: target/mesos.built target/debian-systemv.built target/debian-systemd.built target/centos-systemd.built target/centos-systemv.built target/ubuntu-upstart.built
+all: target/mesos.built target/debian8.built target/centos-systemd.built target/centos-systemv.built target/ubuntu-upstart.built
